title: nadrojisk.com
email:
description: Homepage of nadrojisk.com

github_username: nadrojisk

minimal_mistakes_skin: dark
# search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting

permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/

timezone: America/Chicago # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

logo: "/assets/images/snowflake.png"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache



footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/auehc"
